WebDev.Web.UI/Pages/Index.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.IdentityModel.Tokens;
using System.Security.Claims;
using WebDev.Application.Contracts.Providers;
using WebDev.Domain.Model.Application;
using WebDev.Web.Common.ViewModels;

namespace WebApplicatieWebdev.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IUserProvider _userProvider;
        private readonly IPersonProvider _personProvider;
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly IMapper _mapper;

        [BindProperty] LoginViewModel LoginForm { get; set; }

        public IndexModel(ILogger<IndexModel> logger,
            IUserProvider userProvider,
            IPersonProvider personProvider,
            IHttpContextAccessor contextAccessor,
            IMapper mapper)
        {
            _logger = logger;
            _userProvider = userProvider;
            _personProvider = personProvider;
            _contextAccessor = contextAccessor;
            _mapper = mapper;
        }

        public async Task<IActionResult> OnPostLoginAsync(string email, string password, CancellationToken cancellationToken = default)
        {
            if (email.IsNullOrEmpty() || password.IsNullOrEmpty())
            {
                ModelState.AddModelError("missingFields", "Email and/or Password fields are not filled in.");
                return Page();
            }

            var result = await _userProvider.VerifyLoginAsync(email, password, cancellationToken);

            if (result == null)
            {
                ModelState.AddModelError("invalidInput", "Email or Password is incorrect.");
                return Page();
            }

            var person = await _personProvider.GetPersonByIdAsync(result.PersonId, cancellationToken);

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, result.Id.ToString()),
                new Claim(ClaimTypes.Name, result.Username),
                new Claim(ClaimTypes.Email, result.Email),
                new Claim(ClaimTypes.GivenName, person.DisplayName)
            };

            var identity = new ClaimsIdentity(claims, "cookie");
            var principal = new ClaimsPrincipal(identity);

            await _contextAccessor.HttpContext.SignInAsync(principal);

            return Page();
        }

        public async Task<IActionResult> OnPostRegisterAsync(RegisterUserViewModel model, CancellationToken cancellationToken = default)
        {
            if (!model.RegisterCheck)
            {
                ModelState.AddModelError("noCheck", "Make sure to agree to the terms before you register!");
            }

            if (model.DisplayName.IsNullOrEmpty() ||
                model.UserName.IsNullOrEmpty() ||
                model.Email.IsNullOrEmpty() ||
                model.Password.IsNullOrEmpty() ||
                model.RepeatPassword.IsNullOrEmpty() ||
                model.Password != model.RepeatPassword)
            {
                ModelState.AddModelError("missingField", "All fields must be filled in, passwords must be equal");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var toCreate = _mapper.Map<User>(model);

            var result = await _userProvider.CreateUserAsync(toCreate, model.DisplayName, cancellationToken);

            if (!result)
            {
                ModelState.AddModelError("existingUser", "Email or Username already exists");
            }

            return Page();
        }

        public async Task OnPostLogoutAsync()
        {
            await _contextAccessor.HttpContext.SignOutAsync();
        }

        public void OnGet()
        {

        }
    }
}

WebDev.Web.UI/Pages/Partials/_Login.cshtml
<section id="loginForm" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <ul class="nav nav-pills nav-justified mb-3" id="ex1" role="tablist">
            <li class="nav-item" role="presentation">
                <a class="nav-link active" id="tab-login" data-mdb-toggle="pill" href="#pills-login" role="tab"
                   aria-controls="pills-login" aria-selected="true">Login</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="tab-register" data-mdb-toggle="pill" href="#pills-register" role="tab"
                   aria-controls="pills-register" aria-selected="false">Register</a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade show active" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
                <form method="post" asp-page-handler="Login">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-outline mb-4">
                        <input type="email" id="email" class="form-control" />
                        <label class="form-label" for="email">Email</label>
                    </div>

                    <div class="form-outline mb-4">
                        <input type="password" id="password" class="form-control" />
                        <label class="form-label" for="password">Password</label>
                    </div>

                    @*<div class="row mb-4">
                        <div class="col-md-6 d-flex justify-content-center">
                            <!-- Simple link -->
                            <a href="#!">Forgot password?</a>
                        </div>
                    </div>*@

                    <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
                </form>
            </div>
            <div class="tab-pane fade" id="pills-register" role="tabpanel" aria-labelledby="tab-register">
                <form method="post" asp-page-handler="Register">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-outline mb-4">
                        <input type="text" id="displayName" class="form-control" />
                        <label class="form-label" for="displayName">Name</label>
                    </div>

                    <div class="form-outline mb-4">
                        <input type="text" id="username" class="form-control" />
                        <label class="form-label" for="username">Username</label>
                    </div>

                    <div class="form-outline mb-4">
                        <input type="email" id="email" class="form-control" />
                        <label class="form-label" for="email">Email</label>
                    </div>

                    <div class="form-outline mb-4">
                        <input type="password" id="password" class="form-control" />
                        <label class="form-label" for="password">Password</label>
                    </div>

                    <div class="form-outline mb-4">
                        <input type="password" id="repeatPassword" class="form-control" />
                        <label class="form-label" for="repeatPassword">Repeat password</label>
                    </div>

                    <div class="form-check d-flex justify-content-center mb-4">
                        <input class="form-check-input me-2" type="checkbox" value="" id="registerCheck" checked
                               aria-describedby="registerCheckHelpText" required="required" />
                        <label class="form-check-label" for="registerCheck">
                            I have read and agree to the terms
                        </label>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block mb-3">Sign in</button>
                </form>
            </div>
        </div>
    </div>
</section>

<script>
    var modal = document.getElementById("loginForm");
    var span = document.getElementsByClassName("close")[0];
    span.onclick = function () {
        modal.style.display = "none";
    }

    window.addEventListener("click", function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    });
</script>