WebDev.Web.UI/Pages/Reversi/Dashboard.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebDev.Application.Contracts.Providers;
using WebDev.Domain.Model.Game;
using WebDev.Web.Common.ViewModels;

namespace WebApplicatieWebdev.Pages.Reversi
{
    public class DashboardModel : PageModel
    {
        private readonly IGameProvider _gameProvider;
        private readonly IMapper _mapper;

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostHostGameAsync(HostGameViewModel hostGameViewModel, CancellationToken cancellationToken = default)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var model = _mapper.Map<HostGameModel>(hostGameViewModel);
            var result = await _gameProvider.HostGameAsync(model, cancellationToken);

            if (result == 0) // Failed to host game
            {
                ModelState.AddModelError("Host Game", "Something went wrong.");
                return Page();
            }

            // Redirect naar lobby
            return Redirect($"/Reversi/Game/{result}");
        }

        public DashboardModel(IGameProvider gameProvider,
            IMapper mapper)
        {
            _gameProvider = gameProvider;
            _mapper = mapper;
        }   
    }
}

WebDev.Web.UI/Pages/Reversi/Game.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebDev.Application.Contracts.Providers;
using WebDev.Domain.Model.Game;
using WebDev.Web.Common.ViewModels;

namespace WebDev.Web.UI.Pages.Reversi
{
    public class GameModel : PageModel
    {
        private readonly IGameProvider _gameProvider;
        private readonly IMapper _mapper;

        [BindProperty] public GameViewModel? GameViewModel { get; set; }
        public void OnGet(int id)
        {

        }

        public async Task<IActionResult> OnGetGameDetailsAsync([FromRoute] int id, CancellationToken cancellationToken = default)
        {
            if (GameViewModel == null)
            {
                GameViewModel = _mapper.Map<GameViewModel>(await _gameProvider.GetGameAsync(id, cancellationToken));
            }

            return new OkObjectResult(GameViewModel);
        }

        public async Task<IActionResult> OnPostPlayMoveAsync(PlayMoveViewModel model, CancellationToken cancellationToken = default)
        {
            if (model.PlayerId == 0)
            {
                return new OkObjectResult(false);
            }

            var result = await _gameProvider.PlayMoveAsync(_mapper.Map<PlayMoveModel>(model), cancellationToken);
            return new OkObjectResult(result);
        }

        public GameModel(IGameProvider gameProvider,
            IMapper mapper)
        {
            _gameProvider = gameProvider;
            _mapper = mapper;
        }
    }
}

WebDev.Web.UI/Pages/Reversi/Partials/_ReversiGameBoard.cshtml
<table id="game-board">
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td><div class="tile black"></div></td>
        <td></td>
        <td><div class="tile white"></div></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td><div class="tile black"></div></td>
        <td><div class="tile black"></div></td>
        <td><div class="tile black"></div></td>
        <td><div class="tile black"></div></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td><div class="tile white"></div></td>
        <td><div class="tile white"></div></td>
        <td><div class="tile black"></div></td>
        <td><div class="tile black"></div></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td><div class="tile black"></div></td>
        <td><div class="tile white"></div></td>
        <td></td>
        <td><div class="tile black"></div></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>

WebDev.Web.UI/Pages/Reversi/Partials/_ReversiHostGamePartial.cshtml
<div id="hostGameModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <form method="post" asp-page-handler="HostGame">
            <div class="form-group row">
                <label class="col-4 col-form-label" for="name">Game name</label>
                <div class="col-8">
                    <input id="name" name="name" placeholder="Name" type="text" class="form-control" aria-describedby="nameHelpBlock">
                    <span id="nameHelpBlock" class="form-text text-muted">Not required</span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-4">Private game</label>
                <div class="col-8">
                    <div class="custom-control custom-checkbox custom-control-inline">
                        <input name="privateGame" id="private_0" type="checkbox" aria-describedby="privateHelpBlock" class="custom-control-input" value="true">
                        <label for="private_0" class="custom-control-label">Private</label>
                    </div>
                    <span id="privateHelpBlock" class="form-text text-muted">(If private, invite player once the lobby has been created)</span>
                </div>
            </div>
            <div class="form-group row">
                <label for="turnlength" class="col-4 col-form-label">Turn length</label>
                <div class="col-8">
                    <select id="turnlength" name="turnlength" aria-describedby="turnlengthHelpBlock" required="required" class="custom-select">
                        <option value="1">1 hour</option>
                        <option value="2">2 hours</option>
                        <option value="8">8 hours</option>
                        <option value="24">1 day</option>
                        <option value="72">3 days</option>
                    </select>
                    <span id="turnlengthHelpBlock" class="form-text text-muted">Select a turn length, if a player has reached the limit, the opponent automatically wins the game</span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-4 col-form-label" for="endDate">End Date</label>
                <div class="col-8">
                    <input name="endDate" class="form-control" type="date" />
                    <span id="endDateHelpBlock" class="form-text text-muted">If the game reaches this date, it will be auto concluded.'</span>
                </div>
            </div>
            <div class="form-group row">
                <div class="offset-4 col-8">
                    <button name="submit" type="submit" class="btn btn-primary">Host Game</button>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    var modal = document.getElementById("hostGameModal");
    var span = document.getElementsByClassName("close")[0];
    span.onclick = function () {
        modal.style.display = "none";
    }

    window.addEventListener("click", function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    });
</script>